"""Completion metadata for SDL language-service helpers."""

from __future__ import annotations

REFERENCE_COMPLETION_TARGETS = {
    ("nodes", "features"): "features",
    ("nodes", "conditions"): "conditions",
    ("nodes", "injects"): "injects",
    ("infrastructure", "links"): "infrastructure",
    ("infrastructure", "dependencies"): "infrastructure",
    ("features", "dependencies"): "features",
    ("conditions", "proposition"): "propositions",
    ("propositions", "subjects"): "targetable",
    ("propositions", "evidence_requirements"): "evidence_requirements",
    ("assertions", "proposition"): "propositions",
    ("events", "assertions"): "assertions",
    ("events", "injects"): "injects",
    ("scripts", "events"): "events",
    ("stories", "scripts"): "scripts",
    ("content", "target"): "nodes",
    ("content", "target_service_ref"): "derived:node_services",
    ("content", "shared_service_relationship_ref"): "relationships",
    ("content", "ordering_content_refs"): "content",
    ("content", "readback_assertion_refs"): "assertions",
    ("content", "evidence_requirement_refs"): "evidence_requirements",
    ("content", "observation_boundary_refs"): "observation_boundaries",
    ("accounts", "node"): "nodes",
    ("accounts", "domain_ref"): "identity_domains",
    ("identity_domains", "authority_account_ref"): "accounts",
    ("identity_forests", "root_domain_ref"): "identity_domains",
    ("identity_forests", "domain_refs"): "identity_domains",
    ("identity_facades", "service_ref"): "targetable",
    ("deployment_cells", "tenant_ref"): "deployment_tenants",
    ("deployment_cells", "node_refs"): "nodes",
    ("relationships", "source"): "targetable",
    ("relationships", "target"): "targetable",
    ("relationships", "controller_refs"): "nodes",
    ("relationships", "mutable_state_refs"): "persistent_volumes",
    ("agents", "entity"): "entities",
    ("agents", "starting_accounts"): "accounts",
    ("agents", "starting_assertions"): "assertions",
    ("agents", "target_ref"): "nodes",
    ("agents", "account_ref"): "accounts",
    ("behavior_specifications", "participant_refs"): "agents",
    ("behavior_specifications", "action_contract_refs"): "action_contracts",
    ("behavior_specifications", "observation_boundary_refs"): "observation_boundaries",
    ("behavior_specifications", "outcome_interpretation_rule_refs"): "outcome_interpretation_rules",
    ("behavior_specifications", "authority_scope_refs"): "targetable",
    ("behavior_specifications", "tool_ref"): "content",
    ("behavior_specifications", "participant_ref"): "agents",
    ("behavior_specifications", "inject_ref"): "injects",
    ("behavior_specifications", "event_ref"): "events",
    ("behavior_specifications", "script_ref"): "scripts",
    ("behavior_specifications", "story_ref"): "stories",
    ("behavior_specifications", "source_item_ref"): "targetable",
    ("behavior_specifications", "result_item_ref"): "targetable",
    ("behavior_specifications", "observation_boundary_ref"): "observation_boundaries",
    ("behavior_specifications", "temporal_constraint_refs"): "temporal_constraints",
    ("behavior_specifications", "evidence_requirement_refs"): "evidence_requirements",
    ("behavior_specifications", "controller_ref"): "agents",
    ("behavior_specifications", "control_authority_scope_refs"): "targetable",
    ("behavior_specifications", "control_evidence_refs"): "targetable",
    ("evidence_requirements", "source_refs"): "targetable",
    ("evidence_requirements", "scope_refs"): "targetable",
    ("evidence_requirements", "channel_refs"): "targetable",
    ("evidence_requirements", "trigger_ref"): "targetable",
    ("evidence_requirements", "boundary_ref"): "targetable",
    ("clocks", "time_domain_ref"): "time_domains",
    ("time_domain_mappings", "source_domain_ref"): "time_domains",
    ("time_domain_mappings", "target_domain_ref"): "time_domains",
    ("time_progression_policies", "clock_ref"): "clocks",
    ("temporal_constraints", "clock_ref"): "clocks",
    ("temporal_constraints", "subject_refs"): "targetable",
    ("objectives", "agent"): "agents",
    ("objectives", "entity"): "entities",
    ("objectives", "targets"): "targetable",
    ("objectives", "depends_on"): "objectives",
    ("objectives", "assertions"): "assertions",
    ("injects", "from_entity"): "entities",
    ("injects", "to_entities"): "entities",
    ("workflows", "start"): "workflow_steps",
    ("workflows", "assertions"): "assertions",
    ("workflows", "procedure_ref"): "action_contracts",
    ("workflows", "scaffold_refs"): "observation_boundaries",
    ("workflows", "allowed_action_families"): "action_contracts",
    ("variation_points", "owner"): "targetable",
    ("variation_points", "reference"): "targetable",
    ("variation_points", "allowed_refs"): "targetable",
    ("variation_points", "point"): "variation_points",
    ("variation_points", "variable"): "variables",
}

SECTION_FIELD_COMPLETIONS = {
    "realization": ("default", "scopes"),
    "nodes": (
        "type",
        "description",
        "os",
        "resources",
        "features",
        "conditions",
        "services",
        "roles",
        "endpoint_persona",
    ),
    "infrastructure": ("count", "links", "dependencies", "properties"),
    "features": ("type", "source", "version", "dependencies"),
    "conditions": ("proposition", "command", "interval", "source", "description"),
    "propositions": (
        "description",
        "subjects",
        "basis",
        "predicate",
        "quantifier",
        "threshold",
        "evidence_requirements",
    ),
    "assertions": ("description", "proposition", "role", "polarity"),
    "entities": ("name", "role", "facts", "entities"),
    "injects": ("source", "from_entity", "to_entities"),
    "events": ("assertions", "injects"),
    "scripts": ("start_time", "end_time", "speed", "events"),
    "stories": ("speed", "scripts"),
    "content": (
        "type",
        "target",
        "format",
        "source",
        "path",
        "items",
        "service_materialization",
    ),
    "accounts": (
        "username",
        "node",
        "password_strength",
        "auth_method",
        "credential_bindings",
        "spn",
        "domain_ref",
    ),
    "identity_domains": ("profile", "dns_name", "netbios_name", "authority_account_ref"),
    "identity_forests": ("root_domain_ref", "domain_refs"),
    "identity_facades": ("service_ref", "protocol"),
    "deployment_tenants": ("description",),
    "deployment_cells": ("tenant_ref", "node_refs", "cross_tenant_isolation"),
    "relationships": (
        "type",
        "source",
        "target",
        "properties",
        "domain_controller",
        "domain_join",
        "forest_trust",
        "identity_federation",
        "carrier_placement",
        "shared_service",
    ),
    "agents": (
        "entity",
        "actions",
        "starting_accounts",
        "starting_assertions",
        "initial_knowledge",
        "interactive_access",
    ),
    "behavior_specifications": (
        "semantic_version",
        "lifecycle_state",
        "participant_refs",
        "participant_role_refs",
        "action_contract_refs",
        "observation_boundary_refs",
        "outcome_interpretation_rule_refs",
        "authority_scope_refs",
        "behavior_mode",
        "mixed_control",
        "realization_profile_ref",
        "backend_feature_support_refs",
        "evidence_contract_refs",
        "tool_affordances",
        "participant_inject_deliveries",
        "extension_policy",
        "extensions",
    ),
    "evidence_requirements": (
        "source_refs",
        "source_class",
        "scope_refs",
        "scope",
        "window",
        "trigger_ref",
        "boundary_ref",
        "boundary_kind",
        "channel",
        "channel_refs",
        "artifact_role",
        "media_types",
        "sensitivity",
        "redaction",
        "integrity",
        "retention",
        "loss_disclosure",
    ),
    "time_domains": ("kind", "tick_period_seconds", "epoch", "visibility", "description"),
    "clocks": (
        "time_domain_ref",
        "authority_kind",
        "authority_ref",
        "monotonicity",
        "supports_pause",
        "supports_reset",
        "supports_jump",
        "description",
    ),
    "time_domain_mappings": (
        "source_domain_ref",
        "target_domain_ref",
        "mapping_kind",
        "scale",
        "offset_ticks",
        "description",
    ),
    "time_progression_policies": (
        "clock_ref",
        "advancement_mode",
        "pacing_ratio",
        "synchronization_mode",
        "step_ticks",
        "drift_bound_ticks",
        "reset_behavior",
        "replay_behavior",
        "description",
    ),
    "temporal_constraints": (
        "constraint_kind",
        "clock_ref",
        "subject_refs",
        "start",
        "end",
        "duration_ticks",
        "cadence_ticks",
        "description",
    ),
    "objectives": ("agent", "entity", "actions", "targets", "success", "window", "depends_on"),
    "workflows": ("start", "steps"),
    "variables": ("type", "default", "required", "allowed_values", "description"),
    "variation_points": (
        "kind",
        "target",
        "domain",
        "alternatives",
        "members",
        "minimum",
        "maximum",
        "precedence",
        "fixed_positions",
        "unit",
        "description",
    ),
}
