"""Closed, typed recipes for backend-generated random values (DSL-435, issue #1276).

A ``random_value`` generated artifact declares *how* a fresh, unpredictable value
is generated - its alphabet/encoding, its size (as a random character count or a
target entropy budget), and an optional bounded literal wrapper such as
``TECHVAULT{<32 hex>}``. The recipe carries no generated bytes: the raw value is
produced by the backend with a cryptographically secure generator and is never
authored into the SDL. This module owns only the portable, value-free recipe and
its self-consistency rules; the artifact model (:mod:`raes.stateful_resources`)
couples the recipe to output sensitivity and the secret-entropy floor.
"""

from __future__ import annotations

import math
from enum import Enum

from pydantic import Field, StrictInt, model_validator
from raes_contracts.random_value_generation import NAMED_ALPHABET_CHARSETS

from ._base import SDLModel

# Minimum effective entropy (bits) required for a ``secret`` random-value output.
# 32 uniform hex characters carry exactly this budget; literal wrappers add none.
SECRET_MIN_ENTROPY_BITS = 128
# Bound on the fully rendered value (prefix + random segment + suffix) so an
# unbounded template can never be authored.
MAX_RENDERED_VALUE_LENGTH = 4096
_MAX_RANDOM_LENGTH = 4096
_MAX_ENTROPY_BITS = 4096
_MAX_AFFIX_LENGTH = 256
_MIN_ALPHABET_SIZE = 2


class NamedAlphabet(str, Enum):
    """Closed set of portable alphabets a random value may draw from.

    Concrete charsets live in :data:`raes_contracts.random_value_generation.NAMED_ALPHABET_CHARSETS`,
    the single source of truth shared with backend generation.
    """

    HEX_LOWER = "hex_lower"
    HEX_UPPER = "hex_upper"
    DIGITS = "digits"
    ALPHA = "alpha"
    ALPHANUMERIC = "alphanumeric"
    BASE32 = "base32"
    BASE58 = "base58"


def _has_control_characters(value: str) -> bool:
    return any(ord(character) < 32 or ord(character) == 127 for character in value)


def _validate_affix(value: str, *, field_name: str) -> str:
    if _has_control_characters(value):
        raise ValueError(f"random value format {field_name} must not contain control characters")
    if len(value) > _MAX_AFFIX_LENGTH:
        raise ValueError(f"random value format {field_name} must be at most {_MAX_AFFIX_LENGTH} characters")
    return value


class RandomValueFormat(SDLModel):
    """Bounded literal wrapper placed around the random segment.

    ``prefix`` and ``suffix`` are literal text (no control characters); the random
    segment is inserted between them. The wrapper contributes no entropy.
    """

    prefix: str = ""
    suffix: str = ""

    @model_validator(mode="after")
    def _validate_affixes(self) -> RandomValueFormat:
        _validate_affix(self.prefix, field_name="prefix")
        _validate_affix(self.suffix, field_name="suffix")
        return self


class RandomValueRecipe(SDLModel):
    """Portable, value-free description of how a random value is generated."""

    alphabet: NamedAlphabet | None = Field(default=None, exclude_if=lambda value: value is None)
    custom_alphabet: str | None = Field(default=None, exclude_if=lambda value: value is None)
    length: StrictInt | None = Field(default=None, ge=1, le=_MAX_RANDOM_LENGTH, exclude_if=lambda value: value is None)
    entropy_bits: StrictInt | None = Field(
        default=None, ge=1, le=_MAX_ENTROPY_BITS, exclude_if=lambda value: value is None
    )
    format: RandomValueFormat | None = Field(default=None, exclude_if=lambda value: value is None)
    min_entropy_bits: StrictInt | None = Field(
        default=None, ge=1, le=_MAX_ENTROPY_BITS, exclude_if=lambda value: value is None
    )

    @model_validator(mode="after")
    def _validate_recipe(self) -> RandomValueRecipe:
        if (self.alphabet is None) == (self.custom_alphabet is None):
            raise ValueError("random value recipe requires exactly one of 'alphabet' or 'custom_alphabet'")
        if self.custom_alphabet is not None:
            self._validate_custom_alphabet(self.custom_alphabet)
        if (self.length is None) == (self.entropy_bits is None):
            raise ValueError("random value recipe requires exactly one of 'length' or 'entropy_bits'")
        self._validate_rendered_size()
        floor = self.min_entropy_bits
        if floor is not None and self.effective_entropy_bits() < floor:
            raise ValueError(f"random value effective entropy is below the declared min_entropy_bits of {floor} bits")
        return self

    @staticmethod
    def _validate_custom_alphabet(custom_alphabet: str) -> None:
        if _has_control_characters(custom_alphabet) or any(character.isspace() for character in custom_alphabet):
            raise ValueError("random value custom_alphabet must not contain control or whitespace characters")
        if len(set(custom_alphabet)) != len(custom_alphabet):
            raise ValueError("random value custom_alphabet must not contain duplicate characters")
        if len(custom_alphabet) < _MIN_ALPHABET_SIZE:
            raise ValueError(f"random value custom_alphabet must have at least {_MIN_ALPHABET_SIZE} characters")

    def charset(self) -> str:
        """Return the concrete alphabet the random segment draws from."""

        if self.alphabet is not None:
            return NAMED_ALPHABET_CHARSETS[self.alphabet.value]
        assert self.custom_alphabet is not None  # noqa: S101 - guaranteed by _validate_recipe
        return self.custom_alphabet

    def _bits_per_character(self) -> float:
        return math.log2(len(self.charset()))

    def random_segment_length(self) -> int:
        """Return the number of random characters the segment contains."""

        if self.length is not None:
            return self.length
        assert self.entropy_bits is not None  # noqa: S101 - guaranteed by _validate_recipe
        return math.ceil(self.entropy_bits / self._bits_per_character())

    def effective_entropy_bits(self) -> float:
        """Return the entropy budget of the random segment (wrapper excluded)."""

        if self.entropy_bits is not None:
            return float(self.entropy_bits)
        assert self.length is not None  # noqa: S101 - guaranteed by _validate_recipe
        return self.length * self._bits_per_character()

    def _validate_rendered_size(self) -> None:
        prefix = self.format.prefix if self.format is not None else ""
        suffix = self.format.suffix if self.format is not None else ""
        rendered = len(prefix) + self.random_segment_length() + len(suffix)
        if rendered > MAX_RENDERED_VALUE_LENGTH:
            raise ValueError(
                f"random value rendered size {rendered} exceeds the maximum of {MAX_RENDERED_VALUE_LENGTH} characters"
            )


__all__ = [
    "MAX_RENDERED_VALUE_LENGTH",
    "NamedAlphabet",
    "RandomValueFormat",
    "RandomValueRecipe",
    "SECRET_MIN_ENTROPY_BITS",
]
