"""Reference-edge expectations, part 1 (split from one registry literal)."""

from __future__ import annotations

from tools.sdl_catalog_parity._paths import (
    _ACCOUNT_VALIDATOR,
    _ARTIFACT_VOLUME_FIELDS,
    _CONTENT_COMPILER,
    _CONTENT_VALIDATOR,
    _DANGLING,
    _DANGLING_CYCLIC,
    _DANGLING_ROLE,
    _DEPLOYMENT_TENANCY_SEMANTICS,
    _DOMAIN_TOPOLOGY_SEMANTICS,
    _ENTERPRISE_IDENTITY_SEMANTICS,
    _INFRASTRUCTURE_VALIDATOR,
    _MAIL_SERVICE_SCOPE,
    _MAIL_VALIDATOR,
    _NODE_ROLES,
    _NODE_VALIDATOR,
    _NON_PRECONDITION_ROLE,
    _PROPOSITION_VALIDATOR,
    _RELATIONSHIP_PROXY_VALIDATOR,
    _RELATIONSHIP_VALIDATOR,
    _SECTION_VALIDATOR,
    _SEMANTIC,
    _SERVICE_MATERIALIZATION_VALIDATOR,
    _STATEFUL_MODEL,
    _STRUCTURAL_MODEL,
    _SWITCH_BACKED,
)

EXPECTATIONS_PART_1: dict[str, tuple[str, str, str, str]] = {
    "nodes.*.features[]": ("features", _SEMANTIC, _DANGLING, _NODE_VALIDATOR),
    "nodes.*.features.*": (
        _NODE_ROLES,
        _SEMANTIC,
        _DANGLING_ROLE,
        _NODE_VALIDATOR,
    ),
    "nodes.*.conditions[]": ("conditions", _SEMANTIC, _DANGLING, _NODE_VALIDATOR),
    "nodes.*.conditions.*": (
        _NODE_ROLES,
        _SEMANTIC,
        _DANGLING_ROLE,
        _NODE_VALIDATOR,
    ),
    "conditions.*.proposition": (
        "propositions",
        _SEMANTIC,
        "fatal dangling or ambiguous when present",
        _PROPOSITION_VALIDATOR,
    ),
    "propositions.*.subjects[]": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _PROPOSITION_VALIDATOR,
    ),
    "propositions.*.evidence_requirements[]": (
        "evidence_requirements",
        _SEMANTIC,
        _DANGLING,
        _PROPOSITION_VALIDATOR,
    ),
    "assertions.*.proposition": (
        "propositions",
        _SEMANTIC,
        _DANGLING,
        _PROPOSITION_VALIDATOR,
    ),
    "nodes.*.injects[]": ("injects", _SEMANTIC, _DANGLING, _NODE_VALIDATOR),
    "nodes.*.injects.*": (
        _NODE_ROLES,
        _SEMANTIC,
        _DANGLING_ROLE,
        _NODE_VALIDATOR,
    ),
    "nodes.*.roles.*.entities[]": (
        "entities",
        _SEMANTIC,
        _DANGLING,
        _SECTION_VALIDATOR,
    ),
    "infrastructure.*.$key": (
        "nodes",
        _SEMANTIC,
        "fatal when no same-named node exists",
        _INFRASTRUCTURE_VALIDATOR,
    ),
    "infrastructure.*.links[]": (
        "infrastructure",
        _SEMANTIC,
        _DANGLING,
        _INFRASTRUCTURE_VALIDATOR,
    ),
    "infrastructure.*.properties[].*": (
        "infrastructure",
        _SEMANTIC,
        "fatal unless the key names a linked switch-backed entry",
        _INFRASTRUCTURE_VALIDATOR,
    ),
    "infrastructure.*.acls[].from_net": (
        "infrastructure",
        _SEMANTIC,
        _SWITCH_BACKED,
        _INFRASTRUCTURE_VALIDATOR,
    ),
    "infrastructure.*.acls[].to_net": (
        "infrastructure",
        _SEMANTIC,
        _SWITCH_BACKED,
        _INFRASTRUCTURE_VALIDATOR,
    ),
    "infrastructure.*.dependencies[]": (
        "infrastructure",
        _SEMANTIC,
        _DANGLING,
        _INFRASTRUCTURE_VALIDATOR,
    ),
    "features.*.dependencies[]": (
        "features",
        _SEMANTIC,
        _DANGLING_CYCLIC,
        _SECTION_VALIDATOR,
    ),
    "entities.*.events[]": ("events", _SEMANTIC, _DANGLING, _SECTION_VALIDATOR),
    "injects.*.from_entity": ("entities", _SEMANTIC, _DANGLING, _SECTION_VALIDATOR),
    "injects.*.to_entities[]": ("entities", _SEMANTIC, _DANGLING, _SECTION_VALIDATOR),
    "events.*.assertions[]": (
        "assertions",
        _SEMANTIC,
        _NON_PRECONDITION_ROLE,
        _PROPOSITION_VALIDATOR,
    ),
    "events.*.injects[]": ("injects", _SEMANTIC, _DANGLING, _SECTION_VALIDATOR),
    "scripts.*.events[]": ("events", _SEMANTIC, _DANGLING, _SECTION_VALIDATOR),
    "stories.*.scripts[]": ("scripts", _SEMANTIC, _DANGLING, _SECTION_VALIDATOR),
    "content.*.target": (
        "nodes",
        _SEMANTIC,
        "fatal unless target is a compute node",
        _CONTENT_VALIDATOR,
    ),
    "content.*.service_materialization.target_service_ref": (
        "derived:node_services",
        _SEMANTIC,
        "fatal unless the exact service exists on the content target compute node",
        _SERVICE_MATERIALIZATION_VALIDATOR,
    ),
    "content.*.service_materialization.shared_service_relationship_ref": (
        "relationships",
        _SEMANTIC,
        "fatal unless a matching typed shared-service relationship owns cross-tenant mutable state/reset",
        _SERVICE_MATERIALIZATION_VALIDATOR,
    ),
    "content.*.service_materialization.ordering_content_refs[]": (
        "content",
        "semantic validation and planner ordering",
        "fatal dangling, self, or cyclic dependency",
        _CONTENT_COMPILER,
    ),
    "content.*.service_materialization.readback_assertion_refs[]": (
        "assertions",
        _SEMANTIC,
        "fatal unless each ref is an observed-state postcondition",
        _SERVICE_MATERIALIZATION_VALIDATOR,
    ),
    "content.*.service_materialization.evidence_requirement_refs[]": (
        "evidence_requirements",
        _SEMANTIC,
        "fatal unless each ref exists and every readback proposition requires it",
        _SERVICE_MATERIALIZATION_VALIDATOR,
    ),
    "content.*.service_materialization.observation_boundary_refs[]": (
        "observation_boundaries",
        _SEMANTIC,
        "fatal dangling ref",
        _SERVICE_MATERIALIZATION_VALIDATOR,
    ),
    "generated_artifacts.*.consumers[].node": (
        "nodes",
        _STRUCTURAL_MODEL,
        _DANGLING,
        _STATEFUL_MODEL,
    ),
    "generated_artifacts.*.ordering_dependencies[]": (
        _ARTIFACT_VOLUME_FIELDS,
        "structural model and planner graph validation",
        _DANGLING_CYCLIC,
        _STATEFUL_MODEL,
    ),
    "generated_artifacts.*.refresh_dependencies[]": (
        _ARTIFACT_VOLUME_FIELDS,
        _STRUCTURAL_MODEL,
        _DANGLING,
        _STATEFUL_MODEL,
    ),
    "persistent_volumes.*.consumers[].node": (
        "nodes",
        _STRUCTURAL_MODEL,
        _DANGLING,
        _STATEFUL_MODEL,
    ),
    "persistent_volumes.*.ordering_dependencies[]": (
        _ARTIFACT_VOLUME_FIELDS,
        "structural model and planner graph validation",
        _DANGLING_CYCLIC,
        _STATEFUL_MODEL,
    ),
    "persistent_volumes.*.refresh_dependencies[]": (
        _ARTIFACT_VOLUME_FIELDS,
        _STRUCTURAL_MODEL,
        _DANGLING,
        _STATEFUL_MODEL,
    ),
    "accounts.*.domain_ref": (
        "identity_domains",
        _SEMANTIC,
        "fatal dangling, ambiguous, or inconsistent topology",
        _DOMAIN_TOPOLOGY_SEMANTICS,
    ),
    "identity_domains.*.authority_account_ref": (
        "accounts",
        _SEMANTIC,
        "fatal dangling, ambiguous, or authority outside domain controllers",
        _DOMAIN_TOPOLOGY_SEMANTICS,
    ),
    "identity_forests.*.root_domain_ref": (
        "identity_domains",
        _SEMANTIC,
        "fatal dangling or root outside declared membership",
        _ENTERPRISE_IDENTITY_SEMANTICS,
    ),
    "identity_forests.*.domain_refs[]": (
        "identity_domains",
        _SEMANTIC,
        "fatal dangling, duplicate, or domain in multiple forests",
        _ENTERPRISE_IDENTITY_SEMANTICS,
    ),
    "identity_facades.*.service_ref": (
        "targetable",
        _SEMANTIC,
        "fatal unless target is a named compute service",
        _ENTERPRISE_IDENTITY_SEMANTICS,
    ),
    "deployment_cells.*.tenant_ref": (
        "deployment_tenants",
        _SEMANTIC,
        _DANGLING,
        _DEPLOYMENT_TENANCY_SEMANTICS,
    ),
    "deployment_cells.*.node_refs[]": (
        "nodes",
        _SEMANTIC,
        "fatal dangling, duplicate, or node in multiple cells",
        _DEPLOYMENT_TENANCY_SEMANTICS,
    ),
    "accounts.*.node": (
        "nodes",
        _SEMANTIC,
        "fatal unless target is a compute node",
        _ACCOUNT_VALIDATOR,
    ),
    "relationships.*.source": (
        "targetable",
        _SEMANTIC,
        "fatal dangling or ambiguous; subtype may narrow domain",
        _RELATIONSHIP_VALIDATOR,
    ),
    "relationships.*.target": (
        "targetable",
        _SEMANTIC,
        "fatal dangling or ambiguous; subtype may narrow domain",
        _RELATIONSHIP_VALIDATOR,
    ),
    "relationships.*.database_access.role_ref": (
        "derived:database_roles",
        _SEMANTIC,
        "fatal outside the target database service",
        _RELATIONSHIP_VALIDATOR,
    ),
    "relationships.*.mail_access.listener_ref": (
        "derived:mail_listeners",
        _SEMANTIC,
        _MAIL_SERVICE_SCOPE,
        _MAIL_VALIDATOR,
    ),
    "relationships.*.mail_access.mailbox_ref": (
        "derived:mailboxes",
        _SEMANTIC,
        _MAIL_SERVICE_SCOPE,
        _MAIL_VALIDATOR,
    ),
    "relationships.*.mail_access.domain_ref": (
        "derived:mail_domains",
        _SEMANTIC,
        _MAIL_SERVICE_SCOPE,
        _MAIL_VALIDATOR,
    ),
    "relationships.*.forwarding_edge.forwarder_ref": (
        "runtime:forwarding_agents",
        _SEMANTIC,
        "fatal dangling or ambiguous across scenario and node scopes",
        _RELATIONSHIP_VALIDATOR,
    ),
    "relationships.*.service_integration.consumer_ref": (
        "runtime:platform_applications",
        _SEMANTIC,
        _DANGLING,
        _RELATIONSHIP_VALIDATOR,
    ),
    "relationships.*.service_integration.engine_ref": (
        "runtime:platform_applications",
        _SEMANTIC,
        _DANGLING,
        _RELATIONSHIP_VALIDATOR,
    ),
    "relationships.*.service_integration.auth_principal_ref": (
        "derived:engine_authorization_principals",
        _SEMANTIC,
        "fatal outside the engine authorization scope",
        _RELATIONSHIP_VALIDATOR,
    ),
    "relationships.*.proxy_upstream.route_ref": (
        "derived:source_application_routes",
        _SEMANTIC,
        "fatal outside the source application",
        _RELATIONSHIP_PROXY_VALIDATOR,
    ),
    "relationships.*.proxy_upstream.upstream_node_ref": (
        "nodes",
        _SEMANTIC,
        _DANGLING,
        _RELATIONSHIP_PROXY_VALIDATOR,
    ),
    "relationships.*.proxy_upstream.upstream_service_ref": (
        "derived:upstream_node_services",
        _SEMANTIC,
        "fatal without a resolvable upstream node and service",
        _RELATIONSHIP_PROXY_VALIDATOR,
    ),
    "relationships.*.domain_join.controller_refs[]": (
        "nodes",
        _SEMANTIC,
        "fatal dangling, ambiguous, or controller outside target domain",
        _DOMAIN_TOPOLOGY_SEMANTICS,
    ),
    "relationships.*.shared_service.mutable_state_refs[]": (
        "persistent_volumes",
        _SEMANTIC,
        "fatal dangling or conflicting state ownership",
        _DEPLOYMENT_TENANCY_SEMANTICS,
    ),
}
