"""Reference-edge expectations, part 2 (split from one registry literal)."""

from __future__ import annotations

from tools.sdl_catalog_parity._paths import (
    _BEHAVIOR_MODEL,
    _BEHAVIOR_SEMANTICS,
    _BEHAVIOR_VALIDATOR,
    _DANGLING,
    _MIXED_CONTROL_IDS,
    _MIXED_CONTROL_MODEL,
    _MIXED_CONTROL_VALIDATOR,
    _NON_PRECONDITION_ROLE,
    _OUTCOME_SEMANTICS,
    _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    _PARTICIPANT_INTERACTIVE_ACCESS_SEMANTICS,
    _PARTICIPANT_SEMANTICS,
    _PARTICIPANT_TEMPORAL_MODEL,
    _PARTICIPANT_VALIDATOR,
    _PROPOSITION_VALIDATOR,
    _SEMANTIC,
    _STALE_LOCAL_REF,
    _STRUCTURAL,
    _STRUCTURAL_SEMANTIC,
    _SWITCH_BACKED,
    _TOOL_AFFORDANCE_VALIDATOR,
)

EXPECTATIONS_PART_2: dict[str, tuple[str, str, str, str]] = {
    "agents.*.entity": ("entities", _SEMANTIC, _DANGLING, _PARTICIPANT_VALIDATOR),
    "agents.*.actions[]": (
        "action_contracts",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_SEMANTICS,
    ),
    "agents.*.starting_accounts[]": (
        "accounts",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.interactive_access.*.target_ref": (
        "nodes",
        _SEMANTIC,
        "fatal dangling, ambiguous, or non-compute target",
        _PARTICIPANT_INTERACTIVE_ACCESS_SEMANTICS,
    ),
    "agents.*.interactive_access.*.account_ref": (
        "accounts",
        _SEMANTIC,
        "fatal dangling, same-node mismatch, or outside participant starting accounts",
        _PARTICIPANT_INTERACTIVE_ACCESS_SEMANTICS,
    ),
    "agents.*.starting_assertions[]": (
        "assertions",
        _SEMANTIC,
        _NON_PRECONDITION_ROLE,
        _PROPOSITION_VALIDATOR,
    ),
    "agents.*.initial_knowledge.hosts[]": (
        "nodes",
        _SEMANTIC,
        "fatal unless the target is a compute node",
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.initial_knowledge.subnets[]": (
        "infrastructure",
        _SEMANTIC,
        _SWITCH_BACKED,
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.initial_knowledge.services[]": (
        "derived:node_services",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.initial_knowledge.accounts[]": (
        "accounts",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.allowed_subnets[]": (
        "infrastructure",
        _SEMANTIC,
        _SWITCH_BACKED,
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.authority_anchors[]": (
        "declared",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.operating_scope[]": (
        "derived:operating_scope",
        _SEMANTIC,
        "fatal dangling or ambiguous outside compute nodes, switch-backed infrastructure, services, and content",
        _PARTICIPANT_VALIDATOR,
    ),
    "agents.*.observation_boundaries[]": (
        "observation_boundaries",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_SEMANTICS,
    ),
    "action_contracts.*.interactions.*.related_actions[]": (
        "action_contracts",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_SEMANTICS,
    ),
    "action_contracts.*.interactions.*.target": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_VALIDATOR,
    ),
    "action_contracts.*.interactions.*.shared_state_refs[]": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_VALIDATOR,
    ),
    "action_contracts.*.temporal_contracts.*.backend_disclosure_refs[]": (
        "derived:backend_timing_disclosures",
        _STRUCTURAL,
        "fatal dangling local disclosure id",
        _PARTICIPANT_TEMPORAL_MODEL,
    ),
    "action_contracts.*.backend_timing_disclosures.*.affected_temporal_ids[]": (
        "derived:temporal_contracts",
        _STRUCTURAL,
        "fatal dangling local temporal id",
        _PARTICIPANT_TEMPORAL_MODEL,
    ),
    "observation_boundaries.*.view_rules.*.information_ref": (
        "derived:boundary_information",
        _SEMANTIC,
        "fatal outside declared boundary information",
        _PARTICIPANT_SEMANTICS,
    ),
    "observation_boundaries.*.view_rules.*.evidence_refs[]": (
        "derived:boundary_evidence",
        _SEMANTIC,
        "fatal outside declared boundary evidence",
        _PARTICIPANT_SEMANTICS,
    ),
    "observation_boundaries.*.view_transitions.*.information_ref": (
        "derived:boundary_view_rules",
        _SEMANTIC,
        "fatal without a matching view rule",
        _PARTICIPANT_SEMANTICS,
    ),
    "observation_boundaries.*.view_transitions.*.evidence_refs[]": (
        "derived:boundary_evidence",
        _SEMANTIC,
        "fatal outside declared boundary evidence",
        _PARTICIPANT_SEMANTICS,
    ),
    "outcome_interpretation_rules.*.source_bindings.*.ref": (
        "action_contracts,objectives,workflows",
        _SEMANTIC,
        "fatal dangling for sdl-bound layers",
        _OUTCOME_SEMANTICS,
    ),
    "outcome_interpretation_rules.*.target_bindings.*.ref": (
        "objectives,workflows",
        _SEMANTIC,
        "fatal dangling for sdl-bound layers",
        _OUTCOME_SEMANTICS,
    ),
    "behavior_specifications.*.participant_refs[]": (
        "agents",
        _SEMANTIC,
        _DANGLING,
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.participant_role_refs[]": (
        "derived:agent_roles",
        _SEMANTIC,
        "fatal unless bound by a referenced participant",
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.action_contract_refs[]": (
        "action_contracts",
        _SEMANTIC,
        _DANGLING,
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.observation_boundary_refs[]": (
        "observation_boundaries",
        _SEMANTIC,
        _DANGLING,
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.outcome_interpretation_rule_refs[]": (
        "outcome_interpretation_rules",
        _SEMANTIC,
        _DANGLING,
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.authority_scope_refs[]": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _BEHAVIOR_VALIDATOR,
    ),
    "behavior_specifications.*.tool_affordances.*.tool_ref": (
        "content",
        _SEMANTIC,
        "fatal dangling, ambiguous, or outside the `scenario-content` tools-and-artifacts reference model",
        _TOOL_AFFORDANCE_VALIDATOR,
    ),
    "behavior_specifications.*.tool_affordances.*.action_contract_refs[]": (
        "action_contracts",
        _SEMANTIC,
        "fatal dangling, outside the owning behavior specification, or outside a resolved participant",
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.tool_affordances.*.observation_boundary_refs[]": (
        "observation_boundaries",
        _SEMANTIC,
        "fatal dangling, outside the owner/participant, or without explicit view classification",
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.participant_ref": (
        "agents",
        _SEMANTIC,
        "fatal dangling or outside the owning behavior specification",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.inject_ref": (
        "injects",
        _SEMANTIC,
        "fatal dangling or outside the anchored event occurrence",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.occurrence.event_ref": (
        "events",
        _SEMANTIC,
        "fatal dangling or not containing the bound inject",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.occurrence.script_ref": (
        "scripts",
        _SEMANTIC,
        "fatal dangling or not containing the anchored event",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.occurrence.story_ref": (
        "stories",
        _SEMANTIC,
        "fatal dangling or not containing the anchored script",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.source_item_ref": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.result_item_ref": (
        "targetable",
        _SEMANTIC,
        "fatal dangling, ambiguous, hidden, or unclassified at the participant boundary",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.observation_boundary_ref": (
        "observation_boundaries",
        _SEMANTIC,
        "fatal dangling or outside the owner/participant",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.temporal_constraint_refs[]": (
        "temporal_constraints",
        _SEMANTIC,
        "fatal dangling or not binding this delivery declaration",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.evidence_requirement_refs[]": (
        "evidence_requirements",
        _SEMANTIC,
        "fatal dangling or not binding this delivery declaration",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.control_transition_ref": (
        _MIXED_CONTROL_IDS,
        _STRUCTURAL_SEMANTIC,
        "fatal dangling, wrong-kind, or incomplete control agreement",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.controller_ref": (
        "agents",
        _SEMANTIC,
        "fatal disagreement with the selected control-transition target controller",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.control_authority_scope_refs[]": (
        "targetable",
        _SEMANTIC,
        "fatal dangling, ambiguous, or disagreement with the selected target-state scope",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.participant_inject_deliveries.*.control_evidence_refs[]": (
        "targetable",
        _SEMANTIC,
        "fatal dangling, control disagreement, or absent evidence-requirement coverage",
        _PARTICIPANT_INJECT_DELIVERY_VALIDATOR,
    ),
    "behavior_specifications.*.behavior_mode": (
        "vocabulary:behavior_mode",
        _STRUCTURAL,
        "fatal invalid vocabulary value",
        _BEHAVIOR_MODEL,
    ),
    "behavior_specifications.*.mixed_control.participant_ref": (
        "agents",
        _SEMANTIC,
        "fatal unless owned by the enclosing behavior specification",
        _MIXED_CONTROL_VALIDATOR,
    ),
    "behavior_specifications.*.mixed_control.controller_states.*.controller_ref": (
        "agents-or-self",
        _SEMANTIC,
        "fatal operator/role/identity impersonation or dangling agent",
        _MIXED_CONTROL_VALIDATOR,
    ),
    "behavior_specifications.*.mixed_control.controller_states.*.authority_basis_refs[]": (
        "derived:controller_authority_anchors",
        _SEMANTIC,
        "fatal dangling, ambiguous, or authority widening",
        _MIXED_CONTROL_VALIDATOR,
    ),
    "behavior_specifications.*.mixed_control.controller_states.*.scope_refs[]": (
        "derived:behavior-and-controller-scope",
        _SEMANTIC,
        "fatal dangling, ambiguous, or scope widening",
        _MIXED_CONTROL_VALIDATOR,
    ),
    "behavior_specifications.*.mixed_control.controller_states.*.evidence_refs[]": (
        "declared",
        _SEMANTIC,
        _DANGLING,
        _MIXED_CONTROL_VALIDATOR,
    ),
    "behavior_specifications.*.mixed_control.transitions.*.from_state_ref": (
        _MIXED_CONTROL_IDS,
        _STRUCTURAL_SEMANTIC,
        _STALE_LOCAL_REF,
        _MIXED_CONTROL_MODEL,
    ),
    "behavior_specifications.*.mixed_control.transitions.*.to_state_ref": (
        _MIXED_CONTROL_IDS,
        _STRUCTURAL_SEMANTIC,
        _STALE_LOCAL_REF,
        _MIXED_CONTROL_MODEL,
    ),
    "behavior_specifications.*.mixed_control.transitions.*.proposal_ref": (
        _MIXED_CONTROL_IDS,
        _STRUCTURAL_SEMANTIC,
        _STALE_LOCAL_REF,
        _MIXED_CONTROL_MODEL,
    ),
    "behavior_specifications.*.mixed_control.transitions.*.evidence_refs[]": (
        "declared",
        _SEMANTIC,
        "fatal dangling, ambiguous, or silent handoff",
        _MIXED_CONTROL_VALIDATOR,
    ),
    "behavior_specifications.*.mixed_control.transitions.*.completion_evidence_refs[]": (
        "declared",
        _SEMANTIC,
        "fatal dangling, ambiguous, or silent handoff",
        _MIXED_CONTROL_VALIDATOR,
    ),
    "behavior_specifications.*.realization_profile_ref": (
        "opaque:realization_profile",
        _STRUCTURAL,
        "fatal invalid reference shape; resolution belongs to realization",
        _BEHAVIOR_MODEL,
    ),
    "behavior_specifications.*.backend_feature_support_refs[]": (
        "registry:behavior_features",
        _SEMANTIC,
        "fatal unsupported feature identifier",
        _BEHAVIOR_SEMANTICS,
    ),
    "behavior_specifications.*.evidence_contract_refs[]": (
        "contract:participant_evidence",
        _SEMANTIC,
        "fatal unknown contract identifier",
        _BEHAVIOR_SEMANTICS,
    ),
}
