"""Reference-edge expectations, part 3 (split from one registry literal)."""

from __future__ import annotations

from tools.sdl_catalog_parity._paths import (
    _DANGLING,
    _DANGLING_CYCLIC,
    _DANGLING_UNREACHABLE,
    _EVIDENCE_VALIDATOR,
    _NON_PRECONDITION_ROLE,
    _OBJECTIVE_SEMANTICS,
    _ORDER_POINT_SCOPE,
    _SEMANTIC,
    _STRUCTURAL,
    _TIME_MODEL_VALIDATOR,
    _VARIATION_MEMBERS,
    _VARIATION_SCOPE,
    _VARIATION_VALIDATOR,
    _WORKFLOW_SEMANTICS,
    _WRONG_SLOT_CANDIDATE,
)

EXPECTATIONS_PART_3: dict[str, tuple[str, str, str, str]] = {
    "evidence_requirements.*.source_refs[]": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _EVIDENCE_VALIDATOR,
    ),
    "evidence_requirements.*.scope_refs[]": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _EVIDENCE_VALIDATOR,
    ),
    "evidence_requirements.*.channel_refs[]": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _EVIDENCE_VALIDATOR,
    ),
    "evidence_requirements.*.trigger_ref": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _EVIDENCE_VALIDATOR,
    ),
    "evidence_requirements.*.boundary_ref": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _EVIDENCE_VALIDATOR,
    ),
    "clocks.*.time_domain_ref": (
        "time_domains",
        _SEMANTIC,
        "fatal dangling",
        _TIME_MODEL_VALIDATOR,
    ),
    "time_domain_mappings.*.source_domain_ref": (
        "time_domains",
        _SEMANTIC,
        "fatal dangling, duplicate, or cyclic mapping",
        _TIME_MODEL_VALIDATOR,
    ),
    "time_domain_mappings.*.target_domain_ref": (
        "time_domains",
        _SEMANTIC,
        "fatal dangling, duplicate, or cyclic mapping",
        _TIME_MODEL_VALIDATOR,
    ),
    "time_progression_policies.*.clock_ref": (
        "clocks",
        _SEMANTIC,
        "fatal dangling or incompatible reset/replay lifecycle",
        _TIME_MODEL_VALIDATOR,
    ),
    "temporal_constraints.*.clock_ref": (
        "clocks",
        _SEMANTIC,
        "fatal dangling",
        _TIME_MODEL_VALIDATOR,
    ),
    "temporal_constraints.*.subject_refs[]": (
        "targetable",
        _SEMANTIC,
        "fatal dangling or ambiguous",
        _TIME_MODEL_VALIDATOR,
    ),
    "variation_points.*.target.variable": (
        "variables",
        _SEMANTIC,
        "fatal dangling or wrong variable type",
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.target.owner": (
        "targetable",
        _SEMANTIC,
        "fatal dangling or wrong slot owner type",
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.domain.allowed_refs[]": (
        "targetable",
        _SEMANTIC,
        _WRONG_SLOT_CANDIDATE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.alternatives.*.reference": (
        "targetable",
        _SEMANTIC,
        _WRONG_SLOT_CANDIDATE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.members.*.reference": (
        "targetable",
        _SEMANTIC,
        _WRONG_SLOT_CANDIDATE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.alternatives.*.requires[].point": (
        "variation_points",
        _SEMANTIC,
        _DANGLING,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.alternatives.*.requires[].members[]": (
        _VARIATION_MEMBERS,
        _SEMANTIC,
        _VARIATION_SCOPE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.alternatives.*.excludes[].point": (
        "variation_points",
        _SEMANTIC,
        _DANGLING,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.alternatives.*.excludes[].members[]": (
        _VARIATION_MEMBERS,
        _SEMANTIC,
        _VARIATION_SCOPE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.members.*.requires[].point": (
        "variation_points",
        _SEMANTIC,
        _DANGLING,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.members.*.requires[].members[]": (
        _VARIATION_MEMBERS,
        _SEMANTIC,
        _VARIATION_SCOPE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.members.*.excludes[].point": (
        "variation_points",
        _SEMANTIC,
        _DANGLING,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.members.*.excludes[].members[]": (
        _VARIATION_MEMBERS,
        _SEMANTIC,
        _VARIATION_SCOPE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.precedence[].before": (
        _VARIATION_MEMBERS,
        _STRUCTURAL,
        _ORDER_POINT_SCOPE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.precedence[].after": (
        _VARIATION_MEMBERS,
        _STRUCTURAL,
        _ORDER_POINT_SCOPE,
        _VARIATION_VALIDATOR,
    ),
    "variation_points.*.fixed_positions.*.$key": (
        _VARIATION_MEMBERS,
        _STRUCTURAL,
        _ORDER_POINT_SCOPE,
        _VARIATION_VALIDATOR,
    ),
    "objectives.*.assigned_participant": (
        "agents",
        _SEMANTIC,
        _DANGLING,
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.owner": ("entities", _SEMANTIC, _DANGLING, _OBJECTIVE_SEMANTICS),
    "objectives.*.actions[]": (
        "action_contracts",
        _SEMANTIC,
        "fatal undeclared contract or outside assigned participant actions",
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.targets[]": (
        "targetable",
        _SEMANTIC,
        _DANGLING,
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.success.assertions[]": (
        "assertions",
        _SEMANTIC,
        "fatal dangling, ambiguous, or precondition role",
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.depends_on[]": (
        "objectives",
        _SEMANTIC,
        _DANGLING_CYCLIC,
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.window.stories[]": (
        "stories",
        _SEMANTIC,
        _DANGLING,
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.window.scripts[]": (
        "scripts",
        _SEMANTIC,
        "fatal dangling or outside referenced stories",
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.window.events[]": (
        "events",
        _SEMANTIC,
        "fatal dangling or outside referenced scripts",
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.window.workflows[]": (
        "workflows",
        _SEMANTIC,
        _DANGLING,
        _OBJECTIVE_SEMANTICS,
    ),
    "objectives.*.window.steps[]": (
        "workflow_steps",
        _SEMANTIC,
        "fatal malformed, dangling, or outside referenced workflows",
        _OBJECTIVE_SEMANTICS,
    ),
    "workflows.*.start": (
        "workflow_steps",
        _SEMANTIC,
        "fatal dangling step",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.when.assertions[]": (
        "assertions",
        _SEMANTIC,
        _NON_PRECONDITION_ROLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.when.objectives[]": (
        "objectives",
        _SEMANTIC,
        _DANGLING,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.when.steps.*.step": (
        "workflow_steps",
        _SEMANTIC,
        "fatal dangling, self-referential, non-executable, or unavailable before evaluation",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.cases.*.when.assertions[]": (
        "assertions",
        _SEMANTIC,
        _NON_PRECONDITION_ROLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.cases.*.when.objectives[]": (
        "objectives",
        _SEMANTIC,
        _DANGLING,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.cases.*.when.steps.*.step": (
        "workflow_steps",
        _SEMANTIC,
        "fatal dangling, self-referential, non-executable, or unavailable before evaluation",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.objective": (
        "objectives",
        _SEMANTIC,
        _DANGLING,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.procedure_ref": (
        "action_contracts",
        _SEMANTIC,
        "fatal dangling or non-procedure granularity",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.scaffold_refs[]": (
        "observation_boundaries",
        _SEMANTIC,
        "fatal dangling or scaffold-incompatible boundary",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.allowed_action_families[]": (
        "action_contracts",
        _SEMANTIC,
        "fatal dangling or non-aggregate granularity",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.next": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.on_success": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.on_failure": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.on_exhausted": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.then": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.else": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.cases.*.next": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.default": (
        "workflow_steps",
        _SEMANTIC,
        _DANGLING_UNREACHABLE,
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.branches[]": (
        "workflow_steps",
        _SEMANTIC,
        "fatal dangling or outside a closed parallel branch",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.join": (
        "workflow_steps",
        _SEMANTIC,
        "fatal dangling, non-join, multiply owned, or outside branch closure",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.workflow": (
        "workflows",
        _SEMANTIC,
        "fatal dangling or cyclic",
        _WORKFLOW_SEMANTICS,
    ),
    "workflows.*.steps.*.compensate_with": (
        "workflows",
        _SEMANTIC,
        "fatal dangling, cyclic, or invalid as a compensation target",
        _WORKFLOW_SEMANTICS,
    ),
}
